language: java

jdk:
  - openjdk6

notifications:
  email:
    - sebastian.kacprzak@byoutline.com

env:
  - JAVA6_HOME=/usr/lib/jvm/java-6-openjdk-amd64 TERM=dumb

after_success:
  - ./gradlew jacocoTestReport coveralls